[app]
news_refresh_seconds = 300
weather_refresh_seconds = 120
max_news_items = 80

[[stations]]
id = 114
label = "Vinga"
enabled = true

[[stations]]
id = 70
label = "Mitholmarna"
enabled = true

[[stations]]
id = 99
label = "Goteborg"
enabled = true

[[stations]]
id = 5
label = "Dalbobron"
enabled = true

[[stations]]
id = 171
label = "Tangudden"
enabled = true

[[feeds]]
url = "https://www.gp.se/rss"
source = "GP"
optional = false

[[feeds]]
url = "https://sverigesradio.se/rss/program/95"
source = "SR"
optional = true

[[feeds]]
url = "https://sverigesradio.se/rss/program/4916"
source = "P4V"
optional = true

[[feeds]]
url = "https://www.svt.se/nyheter/lokalt/vast/rss"
source = "SVT"
optional = true

[[feeds]]
url = "https://rss.aftonbladet.se/rss2/small/pages/sections/senastenytt/"
source = "AB"
optional = true

[[feeds]]
url = "https://feeds.expressen.se/nyheter/"
source = "EX"
optional = true

[[feeds]]
url = "https://www.mynewsdesk.com/se/goteborgsstad/pressreleases.rss"
source = "GOT"
optional = true

[[feeds]]
url = "https://www.mynewsdesk.com/se/sos_alarm/pressreleases.rss"
source = "SOS"
optional = true

[smhi]
enabled = true
counties = [14, 13]

[krisinformation]
enabled = true
counties = [14, 13]

[vma]
enabled = true

[bohuslaningen]
enabled = true

[stromstadstidning]
enabled = true
