[app]
news_refresh_seconds = 300
weather_refresh_seconds = 120
max_news_items = 80

[[stations]]
id = 114
label = "Vinga"

[[stations]]
id = 70
label = "Mitholmarna"

[[stations]]
id = 99
label = "Goteborg"

[[stations]]
id = 5
label = "Dalbobron"

[[stations]]
id = 171
label = "Tangudden"

[[feeds]]
url = "https://www.gp.se/rss"
source = "GP"
optional = false

[[feeds]]
url = "https://www.bohuslaningen.se/rss"
source = "BL"
optional = false

[[feeds]]
url = "https://api.sr.se/api/rss/program/95"
source = "SR"
optional = true

[[feeds]]
url = "https://sverigesradio.se/rss/program/4916"
source = "P4V"
optional = true

[[feeds]]
url = "https://www.svt.se/rss.xml"
source = "SVT"
optional = true

[[feeds]]
url = "https://rss.aftonbladet.se/rss2/small/pages/sections/senastenytt/"
source = "AB"
optional = true

[[feeds]]
url = "https://feeds.expressen.se/nyheter/"
source = "EX"
optional = true

[smhi]
enabled = true
counties = [14, 13]
